social:
- {icon: 'github', link: 'https://www.github.com/fcontatto'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/felipe-c-99a18464/'}
- {icon: 'envelope', link: 'mailto:fecontatto@gmail.com'}
